apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: bookstore
  labels:
    app: mongodb
    component: database
spec:
  serviceName: mongodb-service
  replicas: 2  # Mínimo 2 réplicas para alta disponibilidad
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        component: database
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: MONGO_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: MONGO_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: "bookstore"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "mongosh --eval 'db.adminCommand(\"ping\")'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "mongosh --eval 'db.adminCommand(\"ping\")'"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "mongosh --eval 'db.adminCommand(\"ping\")'"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes:
      - name: mongodb-config
        configMap:
          name: mongodb-config
      # Configuración de anti-afinidad para distribuir réplicas en diferentes nodos
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mongodb
              topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "gp2"  # AWS EBS
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: bookstore
  labels:
    app: mongodb
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
  # Configuración de sesión para balanceo de carga
  sessionAffinity: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: bookstore
  labels:
    app: mongodb
    component: database
data:
  mongod.conf: |
    # MongoDB configuration for production
    storage:
      dbPath: /data/db
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          cacheSizeGB: 0.5
          journalCompressor: snappy
          directoryForIndexes: true
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true
    
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
      logRotate: reopen
      verbosity: 0
    
    net:
      port: 27017
      bindIp: 0.0.0.0
      maxIncomingConnections: 200
    
    processManagement:
      fork: false
      pidFilePath: /var/run/mongodb/mongod.pid
    
    replication:
      replSetName: "rs0"
    
    security:
      authorization: enabled
    
    operationProfiling:
      slowOpThresholdMs: 1000
      mode: slowOp

