apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: bookstore
  labels:
    app: review-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: <ECR-REPO>/review-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "5002"
        - name: SERVICE_NAME
          value: "review-service"
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: RABBITMQ_PASS
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb-service:27017/"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: MONGO_PASSWORD
        - name: MONGO_DB
          value: "review_db"
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: USER_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: bookstore
  labels:
    app: review-service
spec:
  type: ClusterIP
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  selector:
    app: review-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: review-service-hpa
  namespace: bookstore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: review-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80



