server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    zuul:
      routes:
        # User Service
        user-service:
          path: /api/users/**
          serviceId: user-service
          stripPrefix: false
          sensitiveHeaders: Cookie,Set-Cookie,Authorization
          
        # Payment Service (Python)
        payment-service-python:
          path: /api/payments-python/**
          url: http://payment-service-python:5000/api/payments
          stripPrefix: false
          sensitiveHeaders: Cookie,Set-Cookie,Authorization
          
        # Payment Service (Java)
        payment-service-java:
          path: /api/payments-java/**
          serviceId: payment-service-java
          stripPrefix: false
          sensitiveHeaders: Cookie,Set-Cookie,Authorization
          
        # Review Service
        review-service:
          path: /api/reviews/**
          serviceId: review-service
          stripPrefix: false
          sensitiveHeaders: Cookie,Set-Cookie,Authorization
          
      # Global configuration
      add-proxy-headers: true
      add-host-header: true
      retryable: true
      
      # Circuit breaker configuration
      hystrix:
        command:
          default:
            execution:
              timeout:
                enabled: true
              isolation:
                thread:
                  timeoutInMilliseconds: 10000
                  
      # Ribbon configuration for load balancing
      ribbon:
        ConnectTimeout: 3000
        ReadTimeout: 10000
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        
  # Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Logging configuration
logging:
  level:
    com.gateway: DEBUG
    com.netflix.zuul: DEBUG
    com.netflix.eureka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger configuration
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

